# Generated by Django 6.0.8 on 2026-09-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_file',
        ),
    ]
