# Generated by Django 6.0.8 on 2026-09-20 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_image'),
        ('courses', '0011_certificate_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignment_submissions', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quiz_submissions', to='accounts.user'),
        ),
    ]
